/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiRoutineRouteImport } from './routes/api/ai-routine'
import { Route as ApiAiCoachRouteImport } from './routes/api/ai-coach'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoutineRoute = ApiAiRoutineRouteImport.update({
  id: '/api/ai-routine',
  path: '/api/ai-routine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCoachRoute = ApiAiCoachRouteImport.update({
  id: '/api/ai-coach',
  path: '/api/ai-coach',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/ai-coach': typeof ApiAiCoachRoute
  '/api/ai-routine': typeof ApiAiRoutineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/ai-coach': typeof ApiAiCoachRoute
  '/api/ai-routine': typeof ApiAiRoutineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/api/ai-coach': typeof ApiAiCoachRoute
  '/api/ai-routine': typeof ApiAiRoutineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/api/ai-coach' | '/api/ai-routine'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/api/ai-coach' | '/api/ai-routine'
  id: '__root__' | '/' | '/dashboard' | '/api/ai-coach' | '/api/ai-routine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ApiAiCoachRoute: typeof ApiAiCoachRoute
  ApiAiRoutineRoute: typeof ApiAiRoutineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-routine': {
      id: '/api/ai-routine'
      path: '/api/ai-routine'
      fullPath: '/api/ai-routine'
      preLoaderRoute: typeof ApiAiRoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-coach': {
      id: '/api/ai-coach'
      path: '/api/ai-coach'
      fullPath: '/api/ai-coach'
      preLoaderRoute: typeof ApiAiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ApiAiCoachRoute: ApiAiCoachRoute,
  ApiAiRoutineRoute: ApiAiRoutineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
